import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Plus, ArrowUp, ArrowUpRight, ChevronDown, ChevronRight, MessageSquare, Bookmark, Settings, HelpCircle, X, Menu, Search, Check, Copy, ThumbsUp, Flag, ExternalLink, Loader2, RotateCcw, Trash2, PanelRightClose, Sparkles, Library, FileText, ArrowLeft, ShieldCheck } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import '@fontsource/manrope/400.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/600.css';
import '@fontsource/manrope/700.css';
import '@fontsource/manrope/800.css';
import '@fontsource/noto-sans-bengali/400.css';
import '@fontsource/noto-sans-bengali/500.css';
import '@fontsource/noto-sans-bengali/600.css';
import './styles.css';

type Book={id:string;level:string;paper:number;title:string;subtitle:string;color:string;description:string;source_note:string;status:string;pages:number|null;chunks:number|null;version:string|null;pdf_available:boolean;quality?:{usable_pages:number;pages:number}};
type Citation={evidence_id:string;page:number;quote:string};
type Answer={id:string;book_id:string;version:string;answer:string;status:string;citations:Citation[];answer_language:string;elapsed_ms:number};
type Turn={id?:string;question:string;result:Answer;session_id?:string;book_id?:string};
type Session={id:string;book_id:string;title:string;created:number};
type Evidence={text:string;page:number;pdf_url:string;book_id:string};
const initialBooks:Book[]=[
 {id:'ssc-2026-bangla-1',level:'SSC',paper:1,title:'বাংলা সাহিত্য',subtitle:'Bangla · First paper',color:'blue',description:'গল্প, কবিতা আর সাহিত্যের জগৎ।'},
 {id:'ssc-2026-bangla-2',level:'SSC',paper:2,title:'বাংলা ব্যাকরণ',subtitle:'Bangla · Second paper',color:'green',description:'ভাষার নিয়ম, ব্যাকরণ ও নির্মিতি।'},
 {id:'hsc-2026-bangla-1',level:'HSC',paper:1,title:'সাহিত্যপাঠ',subtitle:'Bangla · First paper',color:'purple',description:'সাহিত্যের গভীরে, নতুন ভাবনায়।'},
 {id:'hsc-2026-bangla-2',level:'HSC',paper:2,title:'বাংলা দ্বিতীয় পত্র',subtitle:'Bangla · Second paper',color:'orange',description:'শুদ্ধ ভাষা, সুন্দর প্রকাশ।'},
].map(b=>({...b,status:'loading',pages:null,chunks:null,version:null,source_note:'',pdf_available:false}));
async function api<T>(path:string,options:RequestInit={}):Promise<T>{
 const res=await fetch('/api/v1'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});
 if(!res.ok){let msg='Could not connect. Please try again.';try{const x=await res.json();msg=typeof x.detail==='string'?x.detail:'Please check your input.'}catch{}throw new Error(msg)}
 if(res.status===204)return undefined as T;return res.json();
}
function Cover({book,small=false}:{book:Book;small?:boolean}){
 return <div className={`cover ${book.color} ${small?'small':''}`} aria-hidden="true"><div className="cover-spine"/><div className="cover-label">{book.level} <span>2026</span></div><div className="cover-name bn">{book.title}</div><div className="cover-paper bn">{book.paper===1?'প্রথম পত্র':'দ্বিতীয় পত্র'}</div><svg className="cover-art" viewBox="0 0 200 120" fill="none"><path d="M20 106c25-28 57-22 78-11 30-37 60-43 84-57M99 115V36M99 81C64 84 51 65 47 41c32-1 48 14 52 40ZM101 64c0-32 19-43 40-48 3 27-10 44-40 48Z" stroke="currentColor" strokeWidth="1.4"/><path d="M100 110c11-27 34-33 63-28-8 25-32 36-63 28ZM97 106c-27-5-42-18-43-37" stroke="currentColor" strokeWidth="1.4"/><circle cx="163" cy="29" r="14" stroke="currentColor" strokeWidth="1"/><path d="M26 110h152" stroke="currentColor" opacity=".5"/></svg><span className="cover-footer">পাঠশালা</span></div>
}
function Dialog({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close()},[]);
 return <dialog ref={ref} className="dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header>{children}</dialog>
}
function App(){
 const [books,setBooks]=useState(initialBooks),[selected,setSelected]=useState(initialBooks[0].id),[view,setView]=useState<'study'|'library'|'saved'>('study');
 const [sessions,setSessions]=useState<Session[]>([]),[session,setSession]=useState<string|null>(null),[turns,setTurns]=useState<Turn[]>([]),[question,setQuestion]=useState(''),[pending,setPending]=useState(''),[busy,setBusy]=useState(false);
 const [language,setLanguage]=useState(localStorage.getItem('answer-language')||'auto'),[filter,setFilter]=useState('All books'),[search,setSearch]=useState(''),[error,setError]=useState(''),[online,setOnline]=useState(false);
 const [modal,setModal]=useState<'settings'|'help'|'book'|null>(null),[mobileNav,setMobileNav]=useState(false),[evidence,setEvidence]=useState<Evidence|null>(null),[evidenceLoading,setEvidenceLoading]=useState(false);
 const [saved,setSaved]=useState<Turn[]>([]),[savedIds,setSavedIds]=useState<Set<string>>(new Set()),[toast,setToast]=useState(''),[status,setStatus]=useState<Record<string,unknown>>({});
 const [opening,setOpening]=useState(false);
 const input=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null),requestId=useRef<{id:string;text:string;language:string}|null>(null);
 const book=books.find(b=>b.id===selected)||books[0];
 const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(''),3000)};
 const refresh=async()=>{try{const b=await api<Book[]>('/corpora');setBooks(b);setOnline(true);const s=await api<Session[]>('/sessions');setSessions(s)}catch{setOnline(false)}};
 useEffect(()=>{refresh();api<Turn[]>('/saved').then(x=>{setSaved(x);setSavedIds(new Set(x.map(t=>t.result.id)))}).catch(()=>{});const t=setInterval(refresh,15000);return()=>clearInterval(t)},[]);
 useEffect(()=>{localStorage.setItem('answer-language',language)},[language]);
 useEffect(()=>{if(turns.length||pending)bottom.current?.scrollIntoView({behavior:'smooth',block:'end'})},[turns,pending]);
 const reset=(id=selected)=>{if(busy)return;setSelected(id);setSession(null);setTurns([]);setQuestion('');setPending('');setError('');setEvidence(null);setView('study');setMobileNav(false);requestId.current=null};
 const openSession=async(s:Session)=>{if(busy||opening)return;setOpening(true);setMobileNav(false);setError('');try{const data=await api<{messages:Turn[]}>('/sessions/'+s.id+'/messages');setSelected(s.book_id);setSession(s.id);setTurns(data.messages);setQuestion('');setEvidence(null);setView('study');requestId.current=null}catch(e){setError((e as Error).message)}finally{setOpening(false)}};
 const submit=async(text=question)=>{
  text=text.trim();if(!text||busy)return;
  if(!online){setError('The study service is offline. Start the backend, then reconnect.');return}
  if(book.status!=='ready'){setError('This book is being prepared. You can browse your library while its index is set up.');return}
  setBusy(true);setPending(text);setQuestion('');setError('');setView('study');
  if(!requestId.current||requestId.current.text!==text||requestId.current.language!==language)requestId.current={id:crypto.randomUUID(),text,language};
  try{let sid=session;if(!sid){const s=await api<{id:string}>('/sessions',{method:'POST',body:JSON.stringify({collection_id:selected})});sid=s.id;setSession(sid)}
   const answer=await api<Answer>(`/sessions/${sid}/messages`,{method:'POST',body:JSON.stringify({text,answer_language:language,client_message_id:requestId.current.id})});
   setTurns(t=>[...t,{question:text,result:answer}]);requestId.current=null;refresh();
  }catch(e){setError((e as Error).message);setQuestion(text)}finally{setPending('');setBusy(false);input.current?.focus()}
 };
 const showEvidence=async(c:Citation,sid=session)=>{if(!sid)return;setEvidenceLoading(true);try{const x=await api<Evidence>(`/sessions/${sid}/evidence/${c.evidence_id}`);setEvidence(x)}catch(e){notify((e as Error).message)}finally{setEvidenceLoading(false)}};
 const toggleSave=async(answer:Answer)=>{const enabled=!savedIds.has(answer.id);try{await api(`/messages/${answer.id}/saved`,{method:'PUT',body:JSON.stringify({enabled})});setSavedIds(s=>{const n=new Set(s);enabled?n.add(answer.id):n.delete(answer.id);return n});setSaved(await api<Turn[]>('/saved'));notify(enabled?'Answer saved to your collection':'Answer removed from saved')}catch(e){notify((e as Error).message)}};
 const feedback=async(id:string,rating:string)=>{try{await api(`/messages/${id}/feedback`,{method:'PUT',body:JSON.stringify({rating})});notify('Feedback recorded. Thank you.')}catch(e){notify((e as Error).message)}};
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);notify('Answer copied')}catch{notify('Clipboard unavailable in this browser')}};
 const deleteSession=async(s:Session)=>{try{await api('/sessions/'+s.id,{method:'DELETE'});if(session===s.id)reset();refresh();const x=await api<Turn[]>('/saved');setSaved(x);setSavedIds(new Set(x.map(t=>t.result.id)));notify('Conversation deleted')}catch(e){notify((e as Error).message)}};
 const bookChoices=books.filter(b=>(filter==='All books'||b.level===filter)&&(`${b.title} ${b.level} ${b.subtitle}`.toLowerCase().includes(search.toLowerCase())));
 const prompts=book.paper===1?['এই বইয়ের একটি কবিতার মূলভাব বুঝিয়ে দাও','গল্পের প্রধান চরিত্র সম্পর্কে জানতে চাই','Explain a passage in simple English']:['সমাস কী? উদাহরণ দিয়ে বুঝিয়ে দাও','শুদ্ধ বানানের নিয়মগুলো বুঝিয়ে দাও','Explain a grammar rule with an example'];
 const renderTurn=(t:Turn,isSaved=false)=><article className="turn" key={t.result.id}><div className="question-row"><span className="avatar">You</span><h3 className="bn">{t.question}</h3></div><div className="answer-row"><div className="assistant-avatar"><BookOpen size={18}/></div><div className="answer-body"><div className="answer-heading"><strong>Pathshala</strong><span>{t.result.status==='answered'?'From your textbook':t.result.status==='needs_clarification'?'A little more context':'Evidence not found'}</span></div><div className="answer-text bn"><ReactMarkdown>{t.result.answer}</ReactMarkdown></div>{t.result.citations.length>0&&<div className="citations-label">Read the source<div className="citations">{t.result.citations.map((c,i)=><button key={c.evidence_id} onClick={()=>showEvidence(c,t.session_id||session)}><FileText size={14}/><span>{i+1}. PDF page {c.page}</span><ArrowUpRight size={13}/></button>)}</div></div>}<div className="answer-actions"><button aria-label="Copy answer" onClick={()=>copy(t.result.answer)}><Copy size={15}/></button><button aria-label={savedIds.has(t.result.id)?'Unsave answer':'Save answer'} className={savedIds.has(t.result.id)?'saved-active':''} onClick={()=>toggleSave(t.result)}><Bookmark size={15} fill={savedIds.has(t.result.id)?'currentColor':'none'}/></button><button aria-label="Helpful answer" onClick={()=>feedback(t.result.id,'helpful')}><ThumbsUp size={15}/></button><button aria-label="Report incorrect answer" onClick={()=>feedback(t.result.id,'incorrect')}><Flag size={15}/></button>{isSaved&&<span>Saved answer</span>}</div></div></div></article>;
 return <div className="app-shell">
  {mobileNav&&<div className="nav-overlay" onClick={()=>setMobileNav(false)}/>}
  <aside className={`sidebar ${mobileNav?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();reset()}}><div className="brand-mark"><BookOpen size={22}/></div><div>পাঠশালা<span>PATHSHALA</span></div></a><button className="new-chat" onClick={()=>reset()} disabled={busy}><Plus size={18}/>New conversation<span>⌘ K</span></button><nav aria-label="Main navigation"><button className={view==='study'?'active':''} onClick={()=>{setView('study');setMobileNav(false)}}><MessageSquare size={18}/>Study companion</button><button className={view==='library'?'active':''} onClick={()=>{setView('library');setMobileNav(false)}}><Library size={18}/>My library<span className="count">4</span></button><button className={view==='saved'?'active':''} onClick={()=>{setView('saved');setMobileNav(false)}}><Bookmark size={18}/>Saved answers{saved.length>0&&<span className="count">{saved.length}</span>}</button></nav><div className="sidebar-divider"/><div className="recent-heading">Recent conversations</div><div className="recent-list">{sessions.length===0?<p className="recent-empty">Your questions will find a home here.</p>:sessions.slice(0,8).map(s=><div className={`recent-item ${session===s.id?'selected':''}`} key={s.id}><button onClick={()=>openSession(s)} disabled={busy}><MessageSquare size={14}/><span>{s.title}</span></button><button className="delete-chat" aria-label={'Delete '+s.title} onClick={()=>deleteSession(s)} disabled={busy}><Trash2 size={13}/></button></div>)}</div><div className="sidebar-bottom"><div className="study-note"><span className="little-spark"><Sparkles size={15}/></span><p>A little curiosity.<br/>A little progress, every day.</p></div><button onClick={()=>{setModal('help');setMobileNav(false)}}><HelpCircle size={17}/>How Pathshala works<ArrowUpRight size={14}/></button><button onClick={()=>{api<Record<string,unknown>>('/status').then(setStatus).catch(()=>{});setModal('settings');setMobileNav(false)}}><Settings size={17}/>Preferences</button><div className="workspace"><div className="workspace-icon">P</div><div>Your study space<small>Personal workspace</small></div><ShieldCheck size={16}/></div></div></aside>
  <div className={`main-shell ${evidence?'with-evidence':''}`}><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobileNav(true)}><Menu size={20}/></button><span>{view==='library'?'My library':view==='saved'?'Saved answers':'Study companion'}</span><ChevronRight size={14}/><span className="topbar-muted">{view==='study'?'Bangla, made clearer':view==='library'?'Your four textbooks':'Keep what helps'}</span></div><button className="source-trust" onClick={()=>setModal('help')}><span className="trust-dot"/>Answers rooted in your books<HelpCircle size={14}/></button></header>
  <main className={view==='study'&&turns.length?'conversation-main':'welcome-main'}>
  {view==='study'&&<>
   {turns.length===0&&!pending?<div className="welcome"><div className="welcome-tag"><span/>YOUR SPACE TO UNDERSTAND</div><h1 className="bn">পড়া হোক একটু সহজ।</h1><p className="welcome-subtitle">Big questions. Small doubts. Let’s work through them together.</p><div className="section-heading"><h2>Start with your textbook</h2><button onClick={()=>setView('library')}>View library<ArrowUpRight size={15}/></button></div><div className="book-picker">{books.map(b=><button className={`book-choice ${selected===b.id?'selected':''}`} key={b.id} onClick={()=>reset(b.id)} aria-pressed={selected===b.id}><Cover book={b} small/><div className="book-choice-info"><span className={`level-label ${b.color}`}>{b.level} 2026</span><strong className="bn">{b.title}</strong><span>{b.paper===1?'First paper':'Second paper'}</span></div><div className="choice-check">{selected===b.id&&<Check size={11}/>}</div></button>)}</div></div>:<div className="conversation-book"><button onClick={()=>reset()} className="icon-button" aria-label="Back to new conversation" disabled={busy}><ArrowLeft size={18}/></button><div className={`book-mini ${book.color}`}><BookOpen size={18}/></div><div><strong className="bn">{book.title}</strong><span>{book.level} 2026 · {book.paper===1?'First':'Second'} paper</span></div><button className="book-details" onClick={()=>setModal('book')}>Book details<ChevronRight size={14}/></button></div>}
   {turns.length>0&&<div className="conversation">{turns.map(t=>renderTurn(t))}</div>}
   {pending&&<div className="turn pending-turn"><div className="question-row"><span className="avatar">You</span><h3 className="bn">{pending}</h3></div><div className="pending-answer" role="status"><div className="assistant-avatar"><BookOpen size={18}/></div><Loader2 size={17} className="spin"/><span>Reading your textbook and finding the right passages…</span></div></div>}
   <div ref={bottom}/>
   <section className={`composer-section ${turns.length||pending?'sticky-composer':''}`}><div className="composer"><textarea ref={input} value={question} maxLength={2000} onChange={e=>{setQuestion(e.target.value);requestId.current=null}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit()}}} placeholder="তোমার প্রশ্নটি এখানে লিখো…" aria-label="Your question" disabled={busy}/><div className="composer-bottom"><button className="selected-book-chip" onClick={()=>setModal('book')}><BookOpen size={14}/>{book.level} · Bangla {book.paper===1?'1st':'2nd'}<ChevronDown size={12}/></button><div className="composer-tools"><label className="language-choice"><span>Answer in</span><select aria-label="Answer language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="auto">Auto</option><option value="bn">বাংলা</option><option value="en">English</option></select></label><button className="send-button" onClick={()=>submit()} aria-label="Send question" disabled={!question.trim()||busy}>{busy?<Loader2 size={20} className="spin"/>:<ArrowUp size={21}/>}</button></div></div></div>{error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>{refresh();setError('')}} aria-label="Dismiss error"><X size={15}/></button></div>}<div className="composer-note"><ShieldCheck size={13}/><span>Grounded in your selected book. Check the source when it matters.</span><span className="keyboard-hint">Enter to send</span></div></section>
   {turns.length===0&&!pending&&<><section className="ideas"><h2>A little inspiration to get started</h2><div className="prompt-grid">{prompts.map((p,i)=><button key={p} onClick={()=>{setQuestion(p);input.current?.focus()}}><span className={`prompt-icon p${i}`}>{i===0?<MessageSquare size={17}/>:i===1?<BookOpen size={17}/>:<Sparkles size={17}/>}</span><span className="bn">{p}</span><ArrowUpRight size={15}/></button>)}</div></section><div className="reading-banner"><div className="banner-illustration"><BookOpen size={35} strokeWidth={1.2}/><span>অ</span></div><div><h3>More than an answer. A way to understand.</h3><p>Ask in বাংলা or English. Follow the explanation. Open the original page.</p></div><button onClick={()=>setModal('help')} aria-label="Learn how Pathshala works"><ArrowUpRight size={20}/></button></div><div className="availability"><span className={`availability-dot ${online&&book.status==='ready'?'ready':''}`}/>{!online?'Connecting to your study service…':book.status==='ready'?`${book.pages} pages available in this book`:'This book is being prepared for study'}<button onClick={()=>setModal('book')}>Source details</button></div></>}
  </>}
  {view==='library'&&<section className="library-page"><div className="page-eyebrow">A bookshelf of possibilities</div><h1>Your Bangla library</h1><p>Four books. Two milestones. One space to make sense of it all.</p><div className="library-toolbar"><div className="tabs">{['All books','SSC','HSC'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a textbook" aria-label="Find a textbook"/></label></div><div className="library-grid">{bookChoices.map(b=><article className="library-book" key={b.id}><button className="cover-button" onClick={()=>reset(b.id)} disabled={busy}><Cover book={b}/></button><div className="library-book-meta"><span className={`level-label ${b.color}`}>{b.level} 2026</span><span>{b.paper===1?'First paper':'Second paper'}</span></div><h2 className="bn">{b.title}</h2><p className="bn">{b.description}</p><div className="book-availability"><span className={`availability-dot ${b.status==='ready'?'ready':''}`}/>{b.status==='ready'?`${b.pages} pages · Ready to study`:'Preparing textbook'}</div><button className="study-book" onClick={()=>reset(b.id)} disabled={busy}>Study this book<ArrowUpRight size={16}/></button></article>)}</div>{bookChoices.length===0&&<div className="empty-state"><Search size={30}/><h2>No matching books</h2><p>Try SSC, HSC, or a Bengali book title.</p></div>}<div className="library-footnote"><ShieldCheck size={17}/><p>Each conversation stays within one book. Source editions and syllabus coverage are shown in book details.</p></div></section>}
  {view==='saved'&&<section className="saved-page"><div className="page-eyebrow">For your next revision</div><h1>Keep the helpful parts.</h1><p>Your saved explanations, with their original sources.</p>{saved.length===0?<div className="empty-state"><div className="empty-icon"><Bookmark size={29}/></div><h2>Your collection starts with a good question.</h2><p>Save an answer while studying and find it here when you need it again.</p><button className="primary-button" onClick={()=>setView('study')}>Ask your first question<ArrowUpRight size={16}/></button></div>:saved.map(t=>renderTurn(t,true))}</section>}
  </main><footer className="main-footer"><span>Made for the way you learn.</span><span>পাঠশালা <span className="footer-separator">/</span> Read. Ask. Understand.</span></footer></div>
  {evidence&&<aside className="evidence-panel" aria-label="Textbook evidence"><header><div><FileText size={18}/><strong>From the textbook</strong></div><button className="icon-button" aria-label="Close evidence" onClick={()=>setEvidence(null)}><PanelRightClose size={19}/></button></header><div className="evidence-book"><span>{books.find(b=>b.id===evidence.book_id)?.level} · PDF page {evidence.page}</span><h2 className="bn">{books.find(b=>b.id===evidence.book_id)?.title}</h2></div><div className="source-excerpt bn">{evidence.text}</div><a className="open-pdf" href={evidence.pdf_url} target="_blank" rel="noreferrer">Open original PDF<ExternalLink size={16}/></a><p className="evidence-disclaimer">Original extracted text. Page numbers refer to the PDF file and may differ from printed numbers.</p></aside>}
  {evidenceLoading&&<div className="toast" role="status"><Loader2 size={16} className="spin"/>Opening source…</div>}{toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {opening&&<div className="toast" role="status"><Loader2 size={16} className="spin"/>Opening conversation…</div>}
  {modal==='help'&&<Dialog title="A companion, with the book open" onClose={()=>setModal(null)}><div className="help-steps">{[[BookOpen,'Choose your textbook','Every conversation uses one selected book. SSC and HSC sources stay separate.'],[MessageSquare,'Ask in your own words','Use বাংলা or English. Ask a follow-up when something still feels unclear.'],[FileText,'See where the answer comes from','Open a source citation to read the original passage and its PDF page.']].map(([Icon,title,body],i)=>{const I=Icon as typeof BookOpen;return <div key={i}><span><I size={20}/></span><section><h3>{title as string}</h3><p>{body as string}</p></section></div>})}</div><div className="dialog-note">Pathshala can make mistakes. It should say when evidence is missing. Use the original textbook to verify important answers.</div></Dialog>}
  {modal==='book'&&<Dialog title="Your selected textbook" onClose={()=>setModal(null)}><div className="book-modal"><Cover book={book} small/><div><span className={`level-label ${book.color}`}>{book.level} 2026 · Paper {book.paper}</span><h2 className="bn">{book.title}</h2><p>{book.status==='ready'?`${book.pages} PDF pages · ${book.chunks} searchable passages`:'Textbook index is being prepared.'}</p></div></div><div className="dialog-note">{book.source_note||'Source information will be available when the backend connects.'}</div>{book.quality&&<p className="source-quality">{book.quality.usable_pages} of {book.quality.pages} pages passed the initial text check. Other pages require review and are excluded from retrieval.</p>}<button className="primary-button" onClick={()=>{setModal(null);setView('library')}}>Choose another book<ArrowUpRight size={16}/></button></Dialog>}
  {modal==='settings'&&<Dialog title="Make this space yours" onClose={()=>setModal(null)}><div className="setting-row"><div><h3>Answer language</h3><p>Auto follows the language of your question.</p></div><select value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Preferred answer language"><option value="auto">Auto</option><option value="bn">বাংলা</option><option value="en">English</option></select></div><div className="setting-row"><div><h3>Conversation privacy</h3><p>Conversations are stored locally for up to 24 hours. Questions and retrieved passages are sent to Gemini to prepare answers.</p></div><ShieldCheck size={20}/></div><details className="technical-details"><summary>Service details</summary><dl>{[['Answer model',status.generator],['Search model',status.embedding],['Retrieval',status.retrieval],['Gemini key',status.gemini_configured?'Configured':'Not configured'],['Reranker',status.reranker_enabled?'Enabled':'Not enabled']].map(([k,v])=><React.Fragment key={String(k)}><dt>{String(k)}</dt><dd>{String(v||'Unavailable')}</dd></React.Fragment>)}</dl></details><button className="secondary-button" onClick={()=>{refresh();notify('Connection refreshed')}}><RotateCcw size={15}/>Refresh connection</button></Dialog>}
 </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
